"""Diagnosis response models — validated output from the pipeline."""

from __future__ import annotations

from pydantic import BaseModel, Field

DISCLAIMER_TEXT = (
    "IMPORTANT: This output is generated by an AI clinical decision support tool. "
    "It has not been reviewed or validated by a physician. "
    "It must not be used as the sole basis for any clinical decision. "
    "Always consult a qualified medical professional."
)


class DiagnosisItem(BaseModel):
    """Single diagnosis entry in the differential."""

    disease_name: str = Field(min_length=1, max_length=200)
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_evidence: list[str] = Field(min_length=1, max_length=10)
    graph_path: list[str] = Field(default_factory=list)
    verified_in_graph: bool = True
    # Populated by gate_evidence_grounding. `grounded_path_entries` is
    # the count of graph_path entries that correspond to edges actually
    # present in the prompt context. `hallucinated_path_entries` is the
    # complement — entries the LLM made up from its world knowledge.
    # These are diagnostic-only fields: we never reject diagnoses based
    # on them. They exist to expose retrieval/grounding quality as a
    # real observability signal instead of relying on graph_path
    # length as a proxy.
    grounded_path_entries: int = 0
    hallucinated_path_entries: int = 0


class DifferentialDiagnosis(BaseModel):
    """Full differential diagnosis output from the LLM."""

    diagnoses: list[DiagnosisItem] = Field(min_length=1, max_length=10)
    reasoning_summary: str = ""


class EmergencyResult(BaseModel):
    """Result from the emergency detection gate."""

    triggered: bool = False
    pattern_name: str = ""
    message: str = ""


class DiagnosisResponse(BaseModel):
    """Final API response envelope."""

    diagnoses: list[DiagnosisItem]
    reasoning_summary: str = ""
    emergency: EmergencyResult = Field(default_factory=EmergencyResult)
    low_context: bool = False
    low_confidence: bool = False
    llm_fallback: bool = False
    treatment_advice_stripped: bool = False
    disclaimer: str = DISCLAIMER_TEXT
    request_id: str = ""
    model_used: str = ""
    prompt_version: str = ""

    # Graph data for frontend visualization
    graph_nodes: list[dict] = Field(default_factory=list)
    graph_edges: list[dict] = Field(default_factory=list)

    # Evidence grounding — aggregate counts across all diagnoses.
    # total_evidence_entries is the sum of graph_path lengths; of those,
    # grounded_evidence_entries are the ones that correspond to edges
    # actually present in `graph_edges` (the context the LLM was given).
    # The ratio is the single most important retrieval-quality metric
    # because it catches LLM world-knowledge papering over retrieval
    # gaps — see app/guardrails/output_validator.gate_evidence_grounding.
    total_evidence_entries: int = 0
    grounded_evidence_entries: int = 0
