"""Diagnosis response models — validated output from the pipeline."""

from __future__ import annotations

from pydantic import BaseModel, Field

DISCLAIMER_TEXT = (
    "IMPORTANT: This output is generated by an AI clinical decision support tool. "
    "It has not been reviewed or validated by a physician. "
    "It must not be used as the sole basis for any clinical decision. "
    "Always consult a qualified medical professional."
)


class DiagnosisItem(BaseModel):
    """Single diagnosis entry in the differential."""

    disease_name: str = Field(min_length=1, max_length=200)
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_evidence: list[str] = Field(min_length=1, max_length=10)
    graph_path: list[str] = Field(default_factory=list)
    verified_in_graph: bool = True


class DifferentialDiagnosis(BaseModel):
    """Full differential diagnosis output from the LLM."""

    diagnoses: list[DiagnosisItem] = Field(min_length=1, max_length=10)
    reasoning_summary: str = ""


class EmergencyResult(BaseModel):
    """Result from the emergency detection gate."""

    triggered: bool = False
    pattern_name: str = ""
    message: str = ""


class DiagnosisResponse(BaseModel):
    """Final API response envelope."""

    diagnoses: list[DiagnosisItem]
    reasoning_summary: str = ""
    emergency: EmergencyResult = Field(default_factory=EmergencyResult)
    low_context: bool = False
    low_confidence: bool = False
    llm_fallback: bool = False
    treatment_advice_stripped: bool = False
    disclaimer: str = DISCLAIMER_TEXT
    request_id: str = ""
    model_used: str = ""
    prompt_version: str = ""

    # Graph data for frontend visualization
    graph_nodes: list[dict] = Field(default_factory=list)
    graph_edges: list[dict] = Field(default_factory=list)
