"""Pipeline Orchestrator — ties all layers together.

Runs the full Graph RAG pipeline:
  1. Input guardrails (gates 2.1–2.5)
  2. Vector search → seed nodes
  3. Graph traversal → subgraph
  4. Context assembly → prompt
  5. LLM reasoning
  6. Output guardrails (gates 6.1–6.5)
"""

from __future__ import annotations

import structlog
from neo4j import AsyncDriver
from qdrant_client import AsyncQdrantClient

from app.core.context_builder import build_messages
from app.core.graph_traversal import traverse_graph
from app.core.llm_client import call_llm
from app.core.vector_search import NoSeedNodesError, get_seed_nodes
from app.guardrails.emergency import check_emergency
from app.guardrails.input_validator import run_input_gates
from app.guardrails.output_validator import run_output_gates
from app.models.diagnosis import DiagnosisResponse
from app.models.patient import PatientIntake
from app.observability.langfuse_client import create_span, create_trace, end_span

logger = structlog.get_logger()


async def run_diagnosis_pipeline(
    intake: PatientIntake,
    neo4j_driver: AsyncDriver,
    qdrant_client: AsyncQdrantClient,
    request_id: str = "",
) -> DiagnosisResponse:
    """Execute the full diagnosis pipeline.

    Args:
        intake: Validated patient intake data.
        neo4j_driver: Neo4j async driver.
        qdrant_client: Qdrant async client.
        request_id: Unique request ID for tracing.

    Returns:
        DiagnosisResponse with diagnoses, graph data, and metadata.
    """
    # Create Langfuse trace
    trace = create_trace(
        name="diagnosis_pipeline",
        request_id=request_id,
        metadata={"symptoms": intake.symptoms[:5]},
    )

    # --- Gate 2.1: Emergency Detection ---
    span = create_span(trace, "emergency_check")
    emergency = check_emergency(intake)
    end_span(span, output_data={"triggered": emergency.triggered, "pattern": emergency.pattern_name})

    if emergency.triggered:
        logger.warning("emergency_short_circuit", pattern=emergency.pattern_name)
        return DiagnosisResponse(
            diagnoses=[],
            emergency=emergency,
            disclaimer=(
                "IMPORTANT: This output is generated by an AI clinical decision support tool. "
                "It has not been reviewed or validated by a physician. "
                "It must not be used as the sole basis for any clinical decision. "
                "Always consult a qualified medical professional."
            ),
            request_id=request_id,
        )

    # --- Gates 2.3–2.5: Input Validation ---
    span = create_span(trace, "input_gates")
    run_input_gates(intake)
    end_span(span, output_data={"status": "passed"})

    # --- Layer 3.1: Vector Search ---
    span = create_span(trace, "vector_search")
    try:
        seed_ids, scored_points = await get_seed_nodes(intake, qdrant_client)
    except NoSeedNodesError as exc:
        end_span(span, output_data={"error": str(exc)}, level="WARNING")
        return DiagnosisResponse(
            diagnoses=[],
            reasoning_summary=str(exc),
            low_context=True,
            disclaimer=(
                "IMPORTANT: This output is generated by an AI clinical decision support tool. "
                "It has not been reviewed or validated by a physician. "
                "It must not be used as the sole basis for any clinical decision. "
                "Always consult a qualified medical professional."
            ),
            request_id=request_id,
        )
    end_span(span, output_data={"seed_count": len(seed_ids)})

    # --- Layer 3.2: Graph Traversal ---
    span = create_span(trace, "graph_traversal")
    nodes, relationships = await traverse_graph(seed_ids, neo4j_driver)
    low_context = len(nodes) < 3
    end_span(span, output_data={"nodes": len(nodes), "relationships": len(relationships)})

    # --- Layer 4: Context Assembly ---
    span = create_span(trace, "context_assembly")
    messages, prompt_version = build_messages(intake, nodes, relationships)
    end_span(span, output_data={"prompt_version": prompt_version})

    # --- Layer 5: LLM Reasoning ---
    span = create_span(trace, "llm_call")
    raw_output, model_used = await call_llm(messages)
    end_span(span, output_data={"model": model_used})

    # Detect fallback — LiteLLM returns "llama-3.3-70b-versatile" without the
    # "groq/" provider prefix, so strip the prefix from the configured primary
    # before comparing.
    from app.config import get_settings
    primary = get_settings().primary_llm
    primary_bare = primary.split("/", 1)[-1] if "/" in primary else primary
    model_bare = model_used.split("/", 1)[-1] if "/" in model_used else model_used
    llm_fallback = model_bare != primary_bare

    # --- Layer 6: Output Guardrails ---
    span = create_span(trace, "output_gates")
    response = await run_output_gates(
        raw_output=raw_output,
        neo4j_driver=neo4j_driver,
        request_id=request_id,
        model_used=model_used,
        prompt_version=prompt_version,
        graph_nodes=nodes,
        graph_edges=relationships,
    )

    response.low_context = low_context
    response.llm_fallback = llm_fallback
    end_span(span, output_data={"diagnoses_count": len(response.diagnoses)})

    logger.info(
        "pipeline_complete",
        diagnoses=len(response.diagnoses),
        model=model_used,
        low_context=low_context,
        llm_fallback=llm_fallback,
    )

    return response
